name: urbanfit
description: A new Flutter project for FitApp

environment:
  sdk: "^3.6.0"

publish_to: "none" # Remove this line if you want to publish to pub.dev

dependencies:
  image_picker: ^0.8.7
  flutter:
    sdk: flutter
  # Для работы с HTTP запросами
  http: ^0.13.4
  # Для хранения данных на устройстве (например, для токенов JWT)
  shared_preferences: ^2.0.15
  # Для работы с безопасным хранением данных
  flutter_secure_storage: ^9.0.0
  # Для работы с конфигурациями через YAML (например, для загрузки конфигурационных файлов)
  yaml: ^3.1.0
  path_provider: ^2.1.5
  mime_type: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.71.0
  video_player: ^2.9.5
  chewie: ^1.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Для анализа кода
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/muscleGroup/chest.png
    - assets/muscleGroup/back.png
    - assets/muscleGroup/shoulders.png
    - assets/muscleGroup/arms.png
    - assets/muscleGroup/abs.png
    - assets/muscleGroup/legs.png
    - assets/exercise/press_bench.png
    - assets/exercise/dumbbell_press.png
    - assets/error.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
